---
title: "ISEE NAC Environmental Justice Paper Award"
output: html_document
---

This ISEE NAC annual award for the <u>best environmental justice paper</u> published in a peer-reviewed journal aims to <b>recognize excellence in and encourage environmental justice research publishing in this area</b>.

<br>

#### Criteria for the award include, but are not limited to:
- Innovation, creativity, originality
- Quality (data, analyses, presentation, argument)
- Impact
  - Local, community-based work
  - National or international in scope
- Relevance to environmental justice goals, including but not limited to characterization of exposure and health disparities, identification of vulnerable subpopulations, estimation of effects among subpopulations impacted by other stressors and in historically excluded communities from environmental epidemiology research, and others.
- Published in the prior 3 years
- First or senior author must be an ISEE NAC member


The winning paper will be selected by the ISEE North American Chapter Executive Council and members from the Anti-Racism Task Force. 
<br>
Authors, editors, and readers may make nominations.  Self-nominations are welcome.
<br>
Reviewer conflicts include co-authors, same affiliation (same department/university), and authors of competing papers.

<br>

#### How to nominate a paper for the ISEE NAC EJ Award:
*Papers nominated for 2021 must have been published in a scientific journal between 1/1/2018 and 12/31/2020.
<br>
The nomination packet includes:

- A brief nomination letter that includes details on how the paper meets the award criteria, including a 50-100 word statement on what makes the paper outstanding
- Copy of the paper


Please send nominations and supporting materials to the ISEE NAC executive council (isee.northamerica@gmail.com) with the subject line: “ISEE NAC EJ Award.” The winning paper will be announced in July of each year. The winner will be asked to present their work on an ISEE NAC webinar in September and receive as award registration to the annual ISEE meeting and a year’s membership.


The deadline for submitting ISEE NAC EJ award nominations is <del>May 15, 2021</del> <ins><b>June 15, 2021</b></ins>.

