---
title: "WEBINARS"
output: html_document
---

We offer webinars on topics ranging from policy to professional development.

The [ISEE Global Education Channel](https://www.youtube.com/channel/UCzW7ZAgwM-h0wWFEESbLlWA){target="_blank"} contains many presentations and training videos.

For the most up-to-date information on upcoming webinars (ISEE, ISEE NAC, CAPE, etc), as well as registration information, please visit ISEE's [Sponsored Events page](https://www.iseepi.org/Public/Career_Development/Workshops_and_Training/Public/Career_Development/Workshops_and_Training.aspx?hkey=c8e3d8dc-163e-4c1b-a65d-e0bb2dccc4ea){target="_blank"}.

<br>

Check out some of our past webinars below!

</br>

**Melissa Smarr, Mary Schubauer-Berigan, Katie Taylor - Non-Academic Career Paths for Environmental Health Researchers - Part 2**

<iframe width="560" height="315" src="https://www.youtube.com/embed/hZZKQpcJ2lk?si=iG1YIEyVFKnhhmBz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

</br>

**Suril Mehta, Erin Haynes, Keeve Nachman - One Year After the East Palestine Train Derailment: A Panel Discussion**

<iframe width="560" height="315" src="https://www.youtube.com/embed/coAI9JfpWJY?si=XAMctV5c4oQ_mVOZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

</br>

**Dania Valvi - PFAS Exposure and Type 2 Diabetes Risk Across the Life-course: The Human Metabolome**

<iframe width="560" height="315" src="https://www.youtube.com/embed/is5uO0uXYO8?si=iUf8PhK88xTXG0Ml" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

</br>

**Carol Shreffler, Abee Boyles, and Joan Casey - NIEHS K99/R00 Webinar**

<iframe width="560" height="315" src="https://www.youtube.com/embed/vFRXD6eK_9o" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

**Rachel Morello-Frosch - The Haves, have-nots, and the health of everyone: What's the connection and why it matters for sustainability and environmental justice**

<iframe width="560" height="315" src="https://www.youtube.com/embed/kiuETY-ap2I" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

**Francine Laden and George Thurston - All Things NIH Study Section**

<iframe width="560" height="315" src="https://www.youtube.com/embed/Tn6cL7I7SpI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>


**Joel Kaufman - A Conversation with EHP's Editor-in-Chief**

<iframe width="560" height="315" src="https://www.youtube.com/embed/CxTrGCIzMLU?si=Ix9YOFDl0PJho0Bu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</br>

**Andrea Baccarelli - Time Management**


<iframe width="560" height="315" src="https://www.youtube.com/embed/yDnxpaqO9s4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

**Emily Copeland - Social Media for Scientists**

<iframe width="560" height="315" src="https://www.youtube.com/embed/Fl0wVuxARf8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

**Eve Gartner - Public Comment 101**

<iframe width="560" height="315" src="https://www.youtube.com/embed/VhnUZrWzM9o" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


</br>

**Amy Kostant- Media Training 101**

<iframe width="560" height="315" src="https://www.youtube.com/embed/xpExhVUa00U" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


</br>


If you have ideas for future webinars, [e-mail](isee.northamerica@gmail.com) or tweet us [\@ISEE_NAC](https://twitter.com/isee_nac?lang=en){target="_blank"}.

</br>
